### ISSUE TITLE
London things to do

### ISSUE THREAD

**Issue by allthedoll** [struszc/London#4]
### Where we're staying
- As of now, we're staying at [Ace Hotel Shoreditch](http://www.acehotel.com/london)
  - This can be changed, but we'll stay here for at least Satellite and Workshop Day, and commute with my colleagues

### My wishlist
- [British Museum](http://www.britishmuseum.org/)
- [Tea with scones at museum](http://www.britishmuseum.org/visiting/eating/great_court_restaurant.aspx)
- [King's Cross HP thing](https://www.harrypotterplatform934.com/pages/about-platform-934)
- [Ballet](http://www.roh.org.uk/events/bvrf2)?
- [Hyde Park](https://en.wikipedia.org/wiki/Hyde_Park,_London)
- [National Gallery](http://www.nationalgallery.org.uk/paintings/collection-overview) art museum
- [Tate Modern](http://www.tate.org.uk/search?type=artwork) more art
- Go somewhere else and get lost?
- Stonehenge

### Resources
- [Steve's recommendations](https://gist.github.com/swinton/ef49abeaff473ecd3151a9ab0fe37648)
- [Nathan's recommended tour](https://evanevanstours.com/sightseeing-tours/london-tours/london-in-one-day/)

#### Things to do/see
1. Tower of London - Out of all the historical london attractions, this is my favorite. It's going to be crowded no matter when you go, though if you want to see the crown jewels, try to go as early as possible and go see that first. Otherwise, the line just gets super long. It's just a pretty unique place and the Beefeater tour is pretty fun. Also, good view of Tower Bridge, walk across it, then along the southbank for a nice afternoon.
2. Museums - There are a lot of museums and they are mostly all free except for special exhibits. My favorite is the Victoria & Albert. If you can go on a friday evening, that's best as they are open late and it's less crowded. It's got history, fashion, art, just a really great mix. Of course, the British Museum, the National Gallery and the Tate Modern are awesome too. The Tate just added a new expansion also it has a great view of St Paul's Cathedral and the Millennium Bridge. 
3. Parks - If you have time, try to make it out to Hampstead Heath. It's like a forest in the city. It's in a very posh area of London but really does feel like a world away. Lots of dog walking. Great view of the city.
4. Random fun things - Stop at Granary Square behind King's Cross if you have time, there are often fun artsy things going on here, it's where the Central St Martin school is. Also lots of good food options here. I would also look into if there's anything interesting going on at the Barbican. It's got a mix of theater, music and art exhibitions.
5. Day trips - Cambridge is a super easy trip, just a 45 minute train ride from King's Cross. It's very cute and very English. Baths is also nice, especially if you want to go to a spa. 

#### Where to eat
1. **Hawksmoor** - There are multiple locations throughout the city. My favorite is in Seven Dials near covent garden. This is my favorite place for Sunday Lunch, which is basically a mini version of Thanksgiving dinner. If you don't want steak, they can serve it with roast chicken. Also, the baked oysters, bone marrow toast and sticky toffee pudding here are my favorites. 
2. **Punjab** - My favorite Indian restaurant in London. I always get the Grandad's Khali Daal and all their specials are good.
3. **Barrafina** - favorite Spanish tapas place. Everything is yummy. There are multiple locations but they are all super busy, so just go early if you don't want to wait a long time. worth it. 
4. **Taberna do Mercado** - This is portugese, go for the custard tart, order the tart as soon as you sit down cuz they only have a few slices a night.
5. **Gelupo** - gelato. Excellent place to stop at after a show in West End.
6. **Boca di Lupo** - Italian tapas, same owners as Gelupo (across the street). The non-pasta dishes are more interesting, but the pasta is super good as well.
7. **Borough Market** - Fun to browse, get good doughnuts at the Bread Ahead stall. Very busy at lunch time, not open everyday, check the website.
8. **Pret A Manger** - This is my favorite fast food place. They are everywhere. The bircher muesli is awesome. most sandwiches are decent. I bought most of my lunches here.
9. There are lots of classic looking pubs around London, most are shit. If you're hanging around Picadilly Circle, the one I recommend there is the Glassblower. It's crowded, but a good vibe and does have a couple of decent beers. If you're into beer and want to check out London brews, go to any of the Craft Beer pubs. The one in Clerkenwell is my favorite, it's usually a bit less crowded, especially if you go before 5.
10. And if you don't know what you want to eat and you're in central london, go to Kingly Court. There's a bunch of restaurants there, so you'll probably find something.

**Comment by struszc** [comment]
I have heard of these dougnuts and they are high on my list. Otherwise your list is perfect... Art, exploring, food and my best bacon. Maybe a spa... I could swing for it. Not necessary though. 
I am super stoked about tea!

**Comment by allthedoll** [comment]
@struszc what kind of spa or spa activities are you looking for? Also we should eat Indian.

**Comment by struszc** [comment]
@allthedoll skip the spa, I have Stonehenge?

**Comment by struszc** [comment]
I will eat Indian... do they serve Alpaca? If so, alpaca your lunch. 
@allthedoll

**Comment by allthedoll** [comment]
- [Sherlock Holmes Pub](http://www.sherlockholmes-stjames.co.uk/)?

**Comment by struszc** [comment]
*Stonehenge*
**With my sister**
![stonehenge](https://cloud.githubusercontent.com/assets/16996975/25619292/f4b89522-2f0f-11e7-8663-5b8b28716d27.jpg)

**Comment by struszc** [comment]
YES! Sherlock HOLMES!

**Comment by allthedoll** [comment]
[Stonehenge trip](https://www.viator.com/tours/London/London-to-Stonehenge-Independent-Afternoon-Trip/d737-3858EE009) is booked for Thursday, May 25.

**Comment by WizardOfAus** [comment]
I would say Tayaabs for Punjab
